---
- hosts: app
  tasks:
  - name: NGINX | Adding NGINX signing key
    apt_key: url=http://nginx.org/keys/nginx_signing.key state=present

  - name: NGINX | Adding sources.list deb url for NGINX
    lineinfile: dest=/etc/apt/sources.list line="deb http://nginx.org/packages/ubuntu xenial nginx"

  - name: NGINX Plus | Adding sources.list deb-src url for NGINX
    lineinfile: dest=/etc/apt/sources.list line="deb-src http://nginx.org/packages/ubuntu xenial nginx"

  - name: NGINX | Updating apt cache and install NGINX
    apt:
      name: nginx
      state: latest
      update_cache: yes

  - name: NGINX | Overwrite conf
    template:
      src: "templates/nginx-default.conf.j2"
      dest: "/etc/nginx/conf.d/default.conf"
      owner: root
      group: root 
      mode: '0644'
    become: true

  - name: NGINX | Restart NGINX
    service:
      name: nginx
      state: restarted

  - name: Node.js app | Install npm
    apt:
      name: npm
      state: latest

  - name: Node.js app | Install PM2
    npm:
      name: pm2
      state: present
      global: yes

  - name: Git Clone Repo
    git: 
      repo: https://github.com/abkunal/Chat-App-using-Socket.io
      dest: "/home/ubuntu/chat"
    become: true

  - name: Running NPM install
    command: npm install
    args:
      chdir: "/home/ubuntu/chat"
    become: true

  - name: Node.js app | PM2 requires Node.js to be available as node
    shell: ln -s /usr/bin/nodejs /usr/bin/node
    ignore_errors: yes

  - name: Node.js app | Start application with PM2
    shell: pm2 start /home/ubuntu/chat/app.js -f